FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV ATLASLY_HOST=0.0.0.0
ENV ATLASLY_PORT=8080
ENV ATLASLY_DEPLOYMENT_TIER=mvp
ENV ATLASLY_STAGE05_RUNTIME_BACKEND=sqlite
ENV ATLASLY_STAGE05_PERSISTENCE_READY=true

COPY . /app

EXPOSE 8080

CMD ["python3", "scripts/webapp_server.py"]
